
package WestBank.views;

import WestBank.Cliente;
import java.util.ArrayList;
import java.util.List;

public class JframeMenu extends javax.swing.JFrame {
    List<Cliente> clientes = new ArrayList<>();
    JInternalFrameRegistro registro = new JInternalFrameRegistro(clientes);
    JInternalFrameBuscar buscar = new JInternalFrameBuscar(clientes);
    JInternalFrameDeposito depositar = new JInternalFrameDeposito(clientes);
    JInternalFrameGirar girar = new JInternalFrameGirar(clientes);
    JInternalFrameTransferir transferir = new JInternalFrameTransferir(clientes);
    
    /**
     * Creates new form JframeMenu
     */
    public JframeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jFrame1 = new javax.swing.JFrame();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        panelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemRegistrarCliente = new javax.swing.JMenuItem();
        jMenuItemVerDatosCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemDepositar = new javax.swing.JMenuItem();
        jMenuItemGirar = new javax.swing.JMenuItem();
        jMenuItemTransferir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setName("panel"); // NOI18N

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenu3.setText("Clientes");

        jMenuItemRegistrarCliente.setText("Registrar cliente");
        jMenuItemRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRegistrarCliente);

        jMenuItemVerDatosCliente.setText("Ver datos de cliente");
        jMenuItemVerDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerDatosClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemVerDatosCliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cuentas");

        jMenuItemDepositar.setText("Depositar");
        jMenuItemDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepositarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDepositar);

        jMenuItemGirar.setText("Girar");
        jMenuItemGirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGirarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemGirar);

        jMenuItemTransferir.setText("Transferir");
        jMenuItemTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransferirActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemTransferir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void closeAllWindows() {
        registro.setVisible(false);
        buscar.setVisible(false);
        depositar.setVisible(false);
        girar.setVisible(false);
        transferir.setVisible(false);
    }
    
    private void jMenuItemRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarClienteActionPerformed
        registro.setSize(500, 300);
        registro.setTitle ("Registro de Clientes");
        this.panelPrincipal.add(registro);
        closeAllWindows();
        registro.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarClienteActionPerformed

    private void jMenuItemVerDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerDatosClienteActionPerformed
        buscar.setSize(860, 300);
        buscar.setTitle ("");
        this.panelPrincipal.add(buscar);  
        closeAllWindows();
        buscar.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerDatosClienteActionPerformed

    private void jMenuItemDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepositarActionPerformed
        depositar.setSize(860, 400);
        depositar.setTitle ("");
        this.panelPrincipal.add(depositar);       
        closeAllWindows();
        depositar.setVisible(true);
    }//GEN-LAST:event_jMenuItemDepositarActionPerformed

    private void jMenuItemGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGirarActionPerformed
        girar.setSize(860, 400);
        girar.setTitle ("");
        this.panelPrincipal.add(girar);       
        closeAllWindows();
        girar.setVisible(true);
    }//GEN-LAST:event_jMenuItemGirarActionPerformed

    private void jMenuItemTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransferirActionPerformed
        transferir.setSize(860, 400);
        transferir.setTitle ("");
        this.panelPrincipal.add(transferir);     
        closeAllWindows();
        transferir.setVisible(true);
    }//GEN-LAST:event_jMenuItemTransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JframeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemDepositar;
    private javax.swing.JMenuItem jMenuItemGirar;
    private javax.swing.JMenuItem jMenuItemRegistrarCliente;
    private javax.swing.JMenuItem jMenuItemTransferir;
    private javax.swing.JMenuItem jMenuItemVerDatosCliente;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
