package WestBank.views;

import WestBank.Cliente;
import WestBank.utils.ValidacionesCuentaBancaria;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class JInternalFrameTransferir extends javax.swing.JInternalFrame {

    List<Cliente> clientes = new ArrayList<>();
    ValidacionesCuentaBancaria validacionCuentaBancaria = new ValidacionesCuentaBancaria();

    /**
     * Creates new form JInternalFrameTransferir
     */
    public JInternalFrameTransferir(List<Cliente> clientes) {
        initComponents();
        JPanelTransferir.setBorder(BorderFactory.createLineBorder(Color.black));
        JPanelTransferir.setSize(400, 300);
        this.clientes = clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelTransferir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTransferirCuentaOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTransferiCuentaDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTransferirMonto = new javax.swing.JTextField();
        jButtonTransferir = new javax.swing.JButton();
        jLabelOK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Ingrese número de cuenta origen");

        jLabel3.setText("Ingrese número de cuenta destino");

        jLabel4.setText("Ingrese monto que desea transferir");

        jButtonTransferir.setText("Transferir");
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelTransferirLayout = new javax.swing.GroupLayout(JPanelTransferir);
        JPanelTransferir.setLayout(JPanelTransferirLayout);
        JPanelTransferirLayout.setHorizontalGroup(
            JPanelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelTransferirLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(JPanelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelOK, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jTransferirCuentaOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTransferiCuentaDestino, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTransferirMonto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTransferir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelTransferirLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        JPanelTransferirLayout.setVerticalGroup(
            JPanelTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTransferirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTransferirCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTransferiCuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTransferirMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTransferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOK)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel1.setText("Transferir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        String cuentaOrigen = jTransferirCuentaOrigen.getText();
        String cuentaDestino = jTransferiCuentaDestino.getText();
        String monto = jTransferirMonto.getText();
        String mensajeError;
        mensajeError = validacionCuentaBancaria.validarMontoDeposito(monto);
        mensajeError = mensajeError + validacionCuentaBancaria.validarExisteCuentaBancariaOrigen(clientes, cuentaOrigen);
        mensajeError = mensajeError + validacionCuentaBancaria.validarCupoCuentaBancariaOrigen(clientes, cuentaOrigen, parseInt(monto));
        mensajeError = mensajeError + validacionCuentaBancaria.validarTipoCuentaBancariaOrigen(clientes, cuentaOrigen, parseInt(monto));
        if ("".equals(mensajeError)) {
            for (Cliente cliente : clientes) {
                if (Integer.toString(cliente.getCuentaBancaria().getNroCuenta()).equals(cuentaOrigen)) {
                    cliente.getCuentaBancaria().setSaldo(cliente.getCuentaBancaria().getSaldo() - parseInt(monto)); 
                    jTransferirCuentaOrigen.setText("");
                    jTransferiCuentaDestino.setText("");
                    jTransferirMonto.setText("");
                    jLabelOK.setText("¡Transferencia realizada correctamente!");
                } 
                if (Integer.toString(cliente.getCuentaBancaria().getNroCuenta()).equals(cuentaDestino)) {
                    cliente.getCuentaBancaria().setSaldo(cliente.getCuentaBancaria().getSaldo() + parseInt(monto)); 
                } 
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, mensajeError);
        }
    }//GEN-LAST:event_jButtonTransferirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelTransferir;
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelOK;
    private javax.swing.JTextField jTransferiCuentaDestino;
    private javax.swing.JTextField jTransferirCuentaOrigen;
    private javax.swing.JTextField jTransferirMonto;
    // End of variables declaration//GEN-END:variables
}
