/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package WestBank.views;

import WestBank.Cliente;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author PROFESOR 16
 */
public class JInternalFrameBuscar extends javax.swing.JInternalFrame {
List<Cliente> clientes = new ArrayList<>();
    /**
     * Creates new form JInternalFrameBuscar
     * @param clientes
     */
    public JInternalFrameBuscar(List<Cliente> clientes) {
        initComponents();
        buscarCliente.setBorder(BorderFactory.createLineBorder(Color.black));
        buscarCliente.setSize(200, 200);
        
        verDatosCliente.setBorder(BorderFactory.createLineBorder(Color.black));
        verDatosCliente.setSize(200, 200);
        
        verDatosCuentaCliente.setBorder(BorderFactory.createLineBorder(Color.black));
        verDatosCuentaCliente.setSize(200, 200);
        
        this.clientes = clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panel1 = new java.awt.Panel();
        buscarCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputRutBuscar = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        LabelBuscarCliente = new javax.swing.JLabel();
        verDatosCliente = new javax.swing.JPanel();
        LabelNombre = new javax.swing.JLabel();
        LabelApellidoMaterno = new javax.swing.JLabel();
        LabelApellidoPaterno = new javax.swing.JLabel();
        jNombreCliente = new javax.swing.JTextField();
        jApellidoPaternoCliente = new javax.swing.JTextField();
        jApellidoMaternoCliente = new javax.swing.JTextField();
        LabelDomicilio = new javax.swing.JLabel();
        LabelApellidoPaterno1 = new javax.swing.JLabel();
        LabelApellidoMaterno1 = new javax.swing.JLabel();
        jTelefonoCliente = new javax.swing.JTextField();
        jDomicilioCliente = new javax.swing.JTextField();
        jComunaCliente = new javax.swing.JTextField();
        verDatosCuentaCliente = new javax.swing.JPanel();
        LabelDomicilio1 = new javax.swing.JLabel();
        jTipoCuentaCliente = new javax.swing.JTextField();
        LabelDomicilio2 = new javax.swing.JLabel();
        jNumeroCuentaCliente = new javax.swing.JTextField();
        LabelDomicilio3 = new javax.swing.JLabel();
        jSaldoCliente = new javax.swing.JTextField();
        LableDatosCuentaCliente = new javax.swing.JLabel();
        LabelDatosClientes = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(550, 300));

        panel1.setLayout(new javax.swing.BoxLayout(panel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Ingrese Rut del Cliente");

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarClienteLayout = new javax.swing.GroupLayout(buscarCliente);
        buscarCliente.setLayout(buscarClienteLayout);
        buscarClienteLayout.setHorizontalGroup(
            buscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(inputRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        buscarClienteLayout.setVerticalGroup(
            buscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LabelBuscarCliente.setText("Buscar Clientes");

        LabelNombre.setText("Nombre:");

        LabelApellidoMaterno.setText("Apellido Materno:");

        LabelApellidoPaterno.setText("Apellido Paterno:");

        jNombreCliente.setEditable(false);

        jApellidoPaternoCliente.setEditable(false);

        jApellidoMaternoCliente.setEditable(false);

        LabelDomicilio.setText("Domicilio:");

        LabelApellidoPaterno1.setText("Comuna:");

        LabelApellidoMaterno1.setText("Teléfono:");

        jTelefonoCliente.setEditable(false);

        jDomicilioCliente.setEditable(false);
        jDomicilioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDomicilioClienteActionPerformed(evt);
            }
        });

        jComunaCliente.setEditable(false);

        javax.swing.GroupLayout verDatosClienteLayout = new javax.swing.GroupLayout(verDatosCliente);
        verDatosCliente.setLayout(verDatosClienteLayout);
        verDatosClienteLayout.setHorizontalGroup(
            verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(verDatosClienteLayout.createSequentialGroup()
                        .addComponent(LabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verDatosClienteLayout.createSequentialGroup()
                        .addComponent(LabelApellidoMaterno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(verDatosClienteLayout.createSequentialGroup()
                        .addComponent(LabelApellidoPaterno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jApellidoPaternoCliente)))
                .addGap(18, 18, 18)
                .addGroup(verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verDatosClienteLayout.createSequentialGroup()
                        .addComponent(LabelApellidoMaterno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verDatosClienteLayout.createSequentialGroup()
                        .addComponent(LabelDomicilio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verDatosClienteLayout.createSequentialGroup()
                        .addComponent(LabelApellidoPaterno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComunaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verDatosClienteLayout.setVerticalGroup(
            verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(jNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDomicilio)
                    .addComponent(jDomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidoPaterno)
                    .addComponent(jApellidoPaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelApellidoPaterno1)
                    .addComponent(jComunaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidoMaterno)
                    .addComponent(jApellidoMaternoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelApellidoMaterno1)
                    .addComponent(jTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        LabelDomicilio1.setText("Número:");

        jTipoCuentaCliente.setEditable(false);

        LabelDomicilio2.setText("Tipo:");

        jNumeroCuentaCliente.setEditable(false);

        LabelDomicilio3.setText("Saldo:");

        jSaldoCliente.setEditable(false);

        javax.swing.GroupLayout verDatosCuentaClienteLayout = new javax.swing.GroupLayout(verDatosCuentaCliente);
        verDatosCuentaCliente.setLayout(verDatosCuentaClienteLayout);
        verDatosCuentaClienteLayout.setHorizontalGroup(
            verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verDatosCuentaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(verDatosCuentaClienteLayout.createSequentialGroup()
                            .addComponent(LabelDomicilio1)
                            .addGap(18, 18, 18)
                            .addComponent(jNumeroCuentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(verDatosCuentaClienteLayout.createSequentialGroup()
                            .addComponent(LabelDomicilio2)
                            .addGap(39, 39, 39)
                            .addComponent(jTipoCuentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(verDatosCuentaClienteLayout.createSequentialGroup()
                        .addComponent(LabelDomicilio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSaldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        verDatosCuentaClienteLayout.setVerticalGroup(
            verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verDatosCuentaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDomicilio1)
                    .addComponent(jNumeroCuentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDomicilio2)
                    .addComponent(jTipoCuentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(verDatosCuentaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDomicilio3)
                    .addComponent(jSaldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        LableDatosCuentaCliente.setText("Datos Cuenta Cliente");

        LabelDatosClientes.setText("Datos Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LabelBuscarCliente)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDatosClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LableDatosCuentaCliente)
                    .addComponent(verDatosCuentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableDatosCuentaCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelDatosClientes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelBuscarCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verDatosCuentaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        JOptionPane.showMessageDialog(rootPane, clientes.size());
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jDomicilioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDomicilioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDomicilioClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelApellidoMaterno;
    private javax.swing.JLabel LabelApellidoMaterno1;
    private javax.swing.JLabel LabelApellidoPaterno;
    private javax.swing.JLabel LabelApellidoPaterno1;
    private javax.swing.JLabel LabelBuscarCliente;
    private javax.swing.JLabel LabelDatosClientes;
    private javax.swing.JLabel LabelDomicilio;
    private javax.swing.JLabel LabelDomicilio1;
    private javax.swing.JLabel LabelDomicilio2;
    private javax.swing.JLabel LabelDomicilio3;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LableDatosCuentaCliente;
    private javax.swing.JPanel buscarCliente;
    private javax.swing.JTextField inputRutBuscar;
    private javax.swing.JTextField jApellidoMaternoCliente;
    private javax.swing.JTextField jApellidoPaternoCliente;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JTextField jComunaCliente;
    private javax.swing.JTextField jDomicilioCliente;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNombreCliente;
    private javax.swing.JTextField jNumeroCuentaCliente;
    private javax.swing.JTextField jSaldoCliente;
    private javax.swing.JTextField jTelefonoCliente;
    private javax.swing.JTextField jTipoCuentaCliente;
    private java.awt.Panel panel1;
    private javax.swing.JPanel verDatosCliente;
    private javax.swing.JPanel verDatosCuentaCliente;
    // End of variables declaration//GEN-END:variables
}
