package WestBank.views;

import WestBank.Cliente;
import WestBank.utils.ValidacionesCliente;
import WestBank.utils.ValidacionesCuentaBancaria;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class JInternalFrameGirar extends javax.swing.JInternalFrame {

    List<Cliente> clientes = new ArrayList<>();
    ValidacionesCliente validacionCliente = new ValidacionesCliente();
    ValidacionesCuentaBancaria validacionCuentaCorriente = new ValidacionesCuentaBancaria();

    /**
     * Creates new form JInternalFrameGirar
     */
    public JInternalFrameGirar(List<Cliente> clientes) {
        initComponents();
        JPanelGiro.setBorder(BorderFactory.createLineBorder(Color.black));
        JPanelGiro.setSize(200, 200);
        this.clientes = clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelGiro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jGirarRut = new javax.swing.JTextField();
        jButtonGirarBuscar = new javax.swing.JButton();
        jLabelTipoCuenta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jGirarMonto = new javax.swing.JTextField();
        jButtonGirar = new javax.swing.JButton();
        jLabelMensajeOK = new javax.swing.JLabel();
        jTextSaldoGiro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Ingrese rut de cliente");

        jButtonGirarBuscar.setText("Buscar");
        jButtonGirarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarBuscarActionPerformed(evt);
            }
        });

        jLabelTipoCuenta.setText("Cuenta de Ahorro");

        jLabel4.setText("Saldo:");

        jLabel5.setText("Ingrese monto que desea girar");

        jButtonGirar.setText("Girar");
        jButtonGirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarActionPerformed(evt);
            }
        });

        jTextSaldoGiro.setEditable(false);

        javax.swing.GroupLayout JPanelGiroLayout = new javax.swing.GroupLayout(JPanelGiro);
        JPanelGiro.setLayout(JPanelGiroLayout);
        JPanelGiroLayout.setHorizontalGroup(
            JPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelGiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelGiroLayout.createSequentialGroup()
                        .addGroup(JPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jGirarRut)
                            .addComponent(jButtonGirarBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelGiroLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextSaldoGiro))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelGiroLayout.createSequentialGroup()
                        .addGroup(JPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonGirar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jGirarMonto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensajeOK, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 56, Short.MAX_VALUE))))
        );
        JPanelGiroLayout.setVerticalGroup(
            JPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelGiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGirarRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGirarBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTipoCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextSaldoGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGirarMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMensajeOK)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setText("Buscar Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(JPanelGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelGiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarActionPerformed
        String rut = jGirarRut.getText();
        String mensajeError = validacionCliente.validacionRutBusqueda(rut);
        String monto = jGirarMonto.getText();
        mensajeError = mensajeError + validacionCuentaCorriente.validarMontoDeposito(monto);

        if ("".equals(mensajeError)) {
            boolean existeCliente = false;
            for (Cliente cliente : clientes) {
                if (cliente.getRut().equals(rut)) {
                    if (cliente.getCuentaBancaria().getSaldo() < parseInt(jGirarMonto.getText())) {
                        JOptionPane.showMessageDialog(rootPane, "El giro supera el monto");
                    } else {
                        int nuevoSaldo = cliente.getCuentaBancaria().getSaldo() - parseInt(jGirarMonto.getText());
                        cliente.getCuentaBancaria().setSaldo(nuevoSaldo);
                        existeCliente = true;
                        jTextSaldoGiro.setText(Integer.toString(cliente.getCuentaBancaria().getSaldo()));
                        jGirarMonto.setText("");
                        jLabelMensajeOK.setText("¡Giro realizado correctamente!");
                    }
                }

            }
            if (!existeCliente) {
                JOptionPane.showMessageDialog(rootPane, "No existen Cliente ingresado");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, mensajeError);
        }
    }//GEN-LAST:event_jButtonGirarActionPerformed

    private void jButtonGirarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarBuscarActionPerformed
        jLabelMensajeOK.setText("");
        jGirarMonto.setText("");
        String rut = jGirarRut.getText();
        String mensajeError = validacionCliente.validacionRutBusqueda(rut);
        if ("".equals(mensajeError)) {
            boolean existeCliente = false;
            for (Cliente cliente : clientes) {
                if (cliente.getRut().equals(rut)) {
                    jLabelTipoCuenta.setText(cliente.getCuentaBancaria().getTipo());
                    jTextSaldoGiro.setText(Integer.toString(cliente.getCuentaBancaria().getSaldo()));
                    existeCliente = true;
                }
            }
            if (!existeCliente) {
                JOptionPane.showMessageDialog(rootPane, "No existen Cliente ingresado");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, mensajeError);
        }
    }//GEN-LAST:event_jButtonGirarBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelGiro;
    private javax.swing.JButton jButtonGirar;
    private javax.swing.JButton jButtonGirarBuscar;
    private javax.swing.JTextField jGirarMonto;
    private javax.swing.JTextField jGirarRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMensajeOK;
    private javax.swing.JLabel jLabelTipoCuenta;
    private javax.swing.JTextField jTextSaldoGiro;
    // End of variables declaration//GEN-END:variables
}
