package WestBank.views;

import WestBank.Cliente;
import WestBank.utils.ValidacionesCliente;
import WestBank.utils.ValidacionesCuentaBancaria;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class JInternalFrameDeposito extends javax.swing.JInternalFrame {

    List<Cliente> clientes = new ArrayList<>();
    ValidacionesCliente validacionCliente = new ValidacionesCliente();
    ValidacionesCuentaBancaria validacionCuentaBancaria = new ValidacionesCuentaBancaria();

    /**
     * Creates new form NewJInternalDeposito
     */
    public JInternalFrameDeposito(List<Cliente> clientes) {
        initComponents();
        FrameDeposito.setBorder(BorderFactory.createLineBorder(Color.black));
        FrameDeposito.setSize(200, 200);
        this.clientes = clientes;
        jLabelMensajeOK.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameDeposito = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDepositoRut = new javax.swing.JTextField();
        jButtonDepositoBuscar = new javax.swing.JButton();
        jLabelTipoCuenta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDepositoMonto = new javax.swing.JTextField();
        jButtonDepositar = new javax.swing.JButton();
        jLabelMensajeOK = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Ingrese rut de cliente");

        jButtonDepositoBuscar.setText("Buscar");
        jButtonDepositoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoBuscarActionPerformed(evt);
            }
        });

        jLabelTipoCuenta.setText("Cuenta de Ahorro");

        jLabel3.setText("Saldo:");

        jLabel4.setText("Ingrese monto que desea depositar");

        jDepositoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepositoMontoActionPerformed(evt);
            }
        });

        jButtonDepositar.setText("Depositar");
        jButtonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositarActionPerformed(evt);
            }
        });

        jTextFieldSaldo.setEditable(false);
        jTextFieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameDepositoLayout = new javax.swing.GroupLayout(FrameDeposito);
        FrameDeposito.setLayout(FrameDepositoLayout);
        FrameDepositoLayout.setHorizontalGroup(
            FrameDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameDepositoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameDepositoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSaldo))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDepositoMonto)
                    .addComponent(jButtonDepositoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDepositoRut)
                    .addComponent(jButtonDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMensajeOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        FrameDepositoLayout.setVerticalGroup(
            FrameDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameDepositoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDepositoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDepositoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTipoCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDepositoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDepositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMensajeOK)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel6.setText("Buscar Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(FrameDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrameDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDepositoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoBuscarActionPerformed
        jLabelMensajeOK.setText("");
        jDepositoMonto.setText("");
        String rut = jDepositoRut.getText();
        String mensajeError = validacionCliente.validacionRutBusqueda(rut);
        if ("".equals(mensajeError)) {
            boolean existeCliente = false;
            for (Cliente cliente : clientes) {
                if (cliente.getRut().equals(rut)) {
                    jLabelTipoCuenta.setText(cliente.getCuentaBancaria().getTipo());
                    jTextFieldSaldo.setText(Integer.toString(cliente.getCuentaBancaria().getSaldo()));
                    existeCliente = true;
                }
            }
            if (!existeCliente) {
                JOptionPane.showMessageDialog(rootPane, "No existen Cliente ingresado");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, mensajeError);
        }

    }//GEN-LAST:event_jButtonDepositoBuscarActionPerformed

    private void jTextFieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaldoActionPerformed

    private void jButtonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositarActionPerformed
        String rut = jDepositoRut.getText();
        String mensajeError = validacionCliente.validacionRutBusqueda(rut);
        String monto = jDepositoMonto.getText();
        mensajeError = mensajeError + validacionCuentaBancaria.validarMontoDeposito(monto);

        if ("".equals(mensajeError)) {
            boolean existeCliente = false;
            for (Cliente cliente : clientes) {
                if (cliente.getRut().equals(rut)) {
                    int nuevoSaldo = cliente.getCuentaBancaria().getSaldo() + parseInt(monto);
                    cliente.getCuentaBancaria().setSaldo(nuevoSaldo);
                    existeCliente = true;
                    jTextFieldSaldo.setText(Integer.toString(cliente.getCuentaBancaria().getSaldo()));
                    jDepositoMonto.setText("");
                    jLabelMensajeOK.setText("¡Deposito realizado correctamente!");
                }
            }
            if (!existeCliente) {
                JOptionPane.showMessageDialog(rootPane, "No existen Cliente ingresado");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, mensajeError);
        }
    }//GEN-LAST:event_jButtonDepositarActionPerformed

    private void jDepositoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepositoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepositoMontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FrameDeposito;
    private javax.swing.JButton jButtonDepositar;
    private javax.swing.JButton jButtonDepositoBuscar;
    private javax.swing.JTextField jDepositoMonto;
    private javax.swing.JTextField jDepositoRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMensajeOK;
    private javax.swing.JLabel jLabelTipoCuenta;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
