/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WestBank;

public class App {

    public static void main(String[] args) {
        Menu menu= new Menu ();
        menu.displayMenu ();
    }
}
